<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Karyawan;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('karyawans')->delete();
        $anggota = [[
            'id_user' => '2',
            'nik' => '0912376124612481',
            'nama' => 'Rakha Ridwan Virgiandi',
            'tempat_lahir' => 'Bandung',
            'tanggal_lahir' => '1990-04-03',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Permata',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Ujung Berung',
            'kelurahan_desa' => 'Pasir Jati',
            'rt' => '2',
            'rw' => '12',
            'agama' => 'Islam',
            'pekerjaan' => 'Mahasiswa',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Indonesia',
        ],[
            'id_user' => '3',
            'nik' => '0012321412412412',
            'nama' => 'Eren Yeager',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1990-01-22',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise No.03',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Cicalengka',
            'kelurahan_desa' => 'Paradise',
            'rt' => '9',
            'rw' => '2',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '4',
            'nik' => '0029587103994857',
            'nama' => 'Mikasa Ackerman',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1994-09-12',
            'jenis_kelamin' => 'W',
            'alamat' => 'Jl. Paradise No.11',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Cicalengka',
            'kelurahan_desa' => 'Paradise',
            'rt' => '9',
            'rw' => '2',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '5',
            'nik' => '0013924211241241',
            'nama' => 'Armin Arlert',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1994-09-12',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise No.23',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Cicalengka',
            'kelurahan_desa' => 'Paradise',
            'rt' => '15',
            'rw' => '8',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '6',
            'nik' => '0031231939131414',
            'nama' => 'Levi Ackerman',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1987-05-11',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise No.07',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Cicalengka',
            'kelurahan_desa' => 'Paradise',
            'rt' => '9',
            'rw' => '1',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '7',
            'nik' => '0043693423532235',
            'nama' => 'Erwin Smith',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1987-05-11',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Cicalengka',
            'kelurahan_desa' => 'Paradise',
            'rt' => '9',
            'rw' => '1',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '8',
            'nik' => '0019548339432843',
            'nama' => 'Rainer Braun',
            'tempat_lahir' => 'Marley',
            'tanggal_lahir' => '1992-09-07',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Marley No.34',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Marley',
            'rt' => '2',
            'rw' => '1',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pejuang Marley',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Marley',
        ],[
            'id_user' => '9',
            'nik' => '0023325040502135',
            'nama' => 'Annie Leonhart',
            'tempat_lahir' => 'Marley',
            'tanggal_lahir' => '1998-11-14',
            'jenis_kelamin' => 'W',
            'alamat' => 'Jl. Marley No.65',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Marley',
            'rt' => '13',
            'rw' => '6',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pejuang Marley',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Marley',
        ],[
            'id_user' => '10',
            'nik' => '0021731371387930',
            'nama' => 'Zeke Yeager',
            'tempat_lahir' => 'Marley',
            'tanggal_lahir' => '1993-05-08',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Marley No.05',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Marley',
            'rt' => '11',
            'rw' => '6',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pejuang Marley',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Marley',
        ],[
            'id_user' => '11',
            'nik' => '0021841391248212',
            'nama' => 'Bertholdt Hoover',
            'tempat_lahir' => 'Marley',
            'tanggal_lahir' => '1993-03-22',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Marley No.53',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Marley',
            'rt' => '2',
            'rw' => '10',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pejuang Marley',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Marley',
        ],[
            'id_user' => '12',
            'nik' => '0023242332943243',
            'nama' => 'Connie Springer',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1996-12-25',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise No.22',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Paradise',
            'rt' => '7',
            'rw' => '9',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],[
            'id_user' => '13',
            'nik' => '0042840021033802',
            'nama' => 'Jean Kristein',
            'tempat_lahir' => 'Paradise',
            'tanggal_lahir' => '1996-04-29',
            'jenis_kelamin' => 'P',
            'alamat' => 'Jl. Paradise No.21',
            'provinsi' => 'Jawa Barat',
            'kabupaten_kota' => 'Bandung',
            'kecamatan' => 'Majalaya',
            'kelurahan_desa' => 'Paradise',
            'rt' => '8',
            'rw' => '1',
            'agama' => 'Protestan',
            'pekerjaan' => 'Pasukan Pengintai',
            'status_perkawinan' => 'Belum Kawin',
            'kewarganegaraan' => 'Paradise',
        ],];
        Karyawan::insert($anggota);
    }
}
